version: '3.8'

services:
  backend:
    image: denpool/bank_app-backend
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Bank_App
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=25032001
      - JWT_SECRET=MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAK1BWVL9bHZOUJThWSFnjO2FvcZMMAHf9LwhTeGs27DBlfL5q07xj03Rd/72HWPnznc3GzEAEaCGNnMEKMcOqJedJSxL2tN88xsC+4g78vJLYNLNYT9E7cISZNSKM0uyjvEcwhrx19ek6Gq4BHRR4XBShqgzQzYCGCYt9Kk7p38JAgMBAAECgYEAjBSWIB9+nnjbdkRtSDDtJO5J
      - SPRINGDOC_SWAGGER_UI_PATH=/bankApp/api/documentation
    networks:
      - spring-postgres

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=Bank_App
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=25032001
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - spring-postgres

volumes:
  db-data:

networks:
  spring-postgres:
